### ISSUE TITLE
Symbols with 0 probability get non-0 prefix length

### ISSUE THREAD

**Issue by kornelski** [sellibitze/packagemerge-rs#2]
Given frequencies:

    [5, 2, 3, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4]

I'd expect optimal lengths to be (under assumption that zero frequency means the symbol will never occur):

    [2, 3, 3, 4, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]

but the actual output is:

    [2, 4, 3, 5, 4, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 2]

I could preprocess input and postprocess output to remove and re-add the zeros, but I'd prefer `package_merge` to handle this internally. Is is possible to incorporate this into the algorithm?

**Comment by sellibitze** [comment]
That's actually intentional. The goal is to assign code words to *all* the symbols minimizing the expected length subject to the max-len constraint. That's how package-merge is defined.

To be honest, I don't like the idea of special-casing the zero-frequency meaning "exclude this symbol in the code book". It would be less general and kind of a violation of the separation of concerns principle. I'd much rather prefer a second function doing this pre/post processing and invoking the first one. Otherwise it would be too difficult to support the original use-case.

**Comment by kornelski** [comment]
OK, no problem

**Comment by kornelski** [comment]
Do you have recommendation how to do it?

I'm basically trying to replace this code:

https://github.com/pornel/lodepng-rust/blob/master/src/huffman.rs#L150

Apart from special handling of 0 it also has workaround for some decoders expecting at least 2 symbols in all cases.
